/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as CommandesIndexRouteImport } from './routes/commandes.index'
import { Route as CommandesOrderIdRouteImport } from './routes/commandes.$orderId'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as ProduitsImportRouteImport } from './routes/produits.import'
import { Route as ProduitsNouveauRouteImport } from './routes/produits.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIndexRoute = CommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesOrderIdRoute = CommandesOrderIdRouteImport.update({
  id: '/commandes/$orderId',
  path: '/commandes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsImportRoute = ProduitsImportRouteImport.update({
  id: '/produits/import',
  path: '/produits/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsNouveauRoute = ProduitsNouveauRouteImport.update({
  id: '/produits/nouveau',
  path: '/produits/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes/': typeof CommandesIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes': typeof CommandesIndexRoute
  '/produits': typeof ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes/': typeof CommandesIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/commandes/$orderId'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes/'
    | '/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/commandes/$orderId'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/commandes/$orderId'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes/'
    | '/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  BoutiquesRoute: typeof BoutiquesRoute
  ClientsRoute: typeof ClientsRoute
  ParametresRoute: typeof ParametresRoute
  CommandesOrderIdRoute: typeof CommandesOrderIdRoute
  ProduitsImportRoute: typeof ProduitsImportRoute
  ProduitsNouveauRoute: typeof ProduitsNouveauRoute
  CommandesIndexRoute: typeof CommandesIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/': {
      id: '/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof CommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/$orderId': {
      id: '/commandes/$orderId'
      path: '/commandes/$orderId'
      fullPath: '/commandes/$orderId'
      preLoaderRoute: typeof CommandesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/import': {
      id: '/produits/import'
      path: '/produits/import'
      fullPath: '/produits/import'
      preLoaderRoute: typeof ProduitsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/nouveau': {
      id: '/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/produits/nouveau'
      preLoaderRoute: typeof ProduitsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  BoutiquesRoute: BoutiquesRoute,
  ClientsRoute: ClientsRoute,
  ParametresRoute: ParametresRoute,
  CommandesOrderIdRoute: CommandesOrderIdRoute,
  ProduitsImportRoute: ProduitsImportRoute,
  ProduitsNouveauRoute: ProduitsNouveauRoute,
  CommandesIndexRoute: CommandesIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
