/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as VueEnsembleRouteImport } from './routes/vue-ensemble'
import { Route as CommandesIndexRouteImport } from './routes/commandes.index'
import { Route as CommandesOrderIdRouteImport } from './routes/commandes.$orderId'
import { Route as FormulairesIndexRouteImport } from './routes/formulaires.index'
import { Route as FormulairesFormIdRouteImport } from './routes/formulaires.$formId'
import { Route as FormulairesCommandeRouteImport } from './routes/formulaires.commande'
import { Route as FormulairesIntegrationsRouteImport } from './routes/formulaires.integrations'
import { Route as FormulairesNouveauRouteImport } from './routes/formulaires.nouveau'
import { Route as FormulairesOffresRouteImport } from './routes/formulaires.offres'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as ProduitsImportRouteImport } from './routes/produits.import'
import { Route as ProduitsNouveauRouteImport } from './routes/produits.nouveau'
import { Route as VitrineStoreIdIndexRouteImport } from './routes/vitrine.$storeId.index'
import { Route as VitrineStoreIdProductIdRouteImport } from './routes/vitrine.$storeId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const VueEnsembleRoute = VueEnsembleRouteImport.update({
  id: '/vue-ensemble',
  path: '/vue-ensemble',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIndexRoute = CommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesOrderIdRoute = CommandesOrderIdRouteImport.update({
  id: '/commandes/$orderId',
  path: '/commandes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesIndexRoute = FormulairesIndexRouteImport.update({
  id: '/formulaires/',
  path: '/formulaires/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesFormIdRoute = FormulairesFormIdRouteImport.update({
  id: '/formulaires/$formId',
  path: '/formulaires/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesCommandeRoute = FormulairesCommandeRouteImport.update({
  id: '/formulaires/commande',
  path: '/formulaires/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesIntegrationsRoute = FormulairesIntegrationsRouteImport.update({
  id: '/formulaires/integrations',
  path: '/formulaires/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesNouveauRoute = FormulairesNouveauRouteImport.update({
  id: '/formulaires/nouveau',
  path: '/formulaires/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesOffresRoute = FormulairesOffresRouteImport.update({
  id: '/formulaires/offres',
  path: '/formulaires/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsImportRoute = ProduitsImportRouteImport.update({
  id: '/produits/import',
  path: '/produits/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsNouveauRoute = ProduitsNouveauRouteImport.update({
  id: '/produits/nouveau',
  path: '/produits/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineStoreIdIndexRoute = VitrineStoreIdIndexRouteImport.update({
  id: '/vitrine/$storeId/',
  path: '/vitrine/$storeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineStoreIdProductIdRoute = VitrineStoreIdProductIdRouteImport.update({
  id: '/vitrine/$storeId/$productId',
  path: '/vitrine/$storeId/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/vue-ensemble': typeof VueEnsembleRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/formulaires/$formId': typeof FormulairesFormIdRoute
  '/formulaires/commande': typeof FormulairesCommandeRoute
  '/formulaires/integrations': typeof FormulairesIntegrationsRoute
  '/formulaires/nouveau': typeof FormulairesNouveauRoute
  '/formulaires/offres': typeof FormulairesOffresRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes/': typeof CommandesIndexRoute
  '/formulaires/': typeof FormulairesIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/vitrine/$storeId/$productId': typeof VitrineStoreIdProductIdRoute
  '/vitrine/$storeId/': typeof VitrineStoreIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/vue-ensemble': typeof VueEnsembleRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/formulaires/$formId': typeof FormulairesFormIdRoute
  '/formulaires/commande': typeof FormulairesCommandeRoute
  '/formulaires/integrations': typeof FormulairesIntegrationsRoute
  '/formulaires/nouveau': typeof FormulairesNouveauRoute
  '/formulaires/offres': typeof FormulairesOffresRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes': typeof CommandesIndexRoute
  '/formulaires': typeof FormulairesIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/vitrine/$storeId/$productId': typeof VitrineStoreIdProductIdRoute
  '/vitrine/$storeId': typeof VitrineStoreIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/boutiques': typeof BoutiquesRoute
  '/clients': typeof ClientsRoute
  '/parametres': typeof ParametresRoute
  '/vue-ensemble': typeof VueEnsembleRoute
  '/commandes/$orderId': typeof CommandesOrderIdRoute
  '/formulaires/$formId': typeof FormulairesFormIdRoute
  '/formulaires/commande': typeof FormulairesCommandeRoute
  '/formulaires/integrations': typeof FormulairesIntegrationsRoute
  '/formulaires/nouveau': typeof FormulairesNouveauRoute
  '/formulaires/offres': typeof FormulairesOffresRoute
  '/produits/import': typeof ProduitsImportRoute
  '/produits/nouveau': typeof ProduitsNouveauRoute
  '/commandes/': typeof CommandesIndexRoute
  '/formulaires/': typeof FormulairesIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/vitrine/$storeId/$productId': typeof VitrineStoreIdProductIdRoute
  '/vitrine/$storeId/': typeof VitrineStoreIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/vue-ensemble'
    | '/commandes/$orderId'
    | '/formulaires/$formId'
    | '/formulaires/commande'
    | '/formulaires/integrations'
    | '/formulaires/nouveau'
    | '/formulaires/offres'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes/'
    | '/formulaires/'
    | '/produits/'
    | '/vitrine/$storeId/$productId'
    | '/vitrine/$storeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/vue-ensemble'
    | '/commandes/$orderId'
    | '/formulaires/$formId'
    | '/formulaires/commande'
    | '/formulaires/integrations'
    | '/formulaires/nouveau'
    | '/formulaires/offres'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes'
    | '/formulaires'
    | '/produits'
    | '/vitrine/$storeId/$productId'
    | '/vitrine/$storeId'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/boutiques'
    | '/clients'
    | '/parametres'
    | '/vue-ensemble'
    | '/commandes/$orderId'
    | '/formulaires/$formId'
    | '/formulaires/commande'
    | '/formulaires/integrations'
    | '/formulaires/nouveau'
    | '/formulaires/offres'
    | '/produits/import'
    | '/produits/nouveau'
    | '/commandes/'
    | '/formulaires/'
    | '/produits/'
    | '/vitrine/$storeId/$productId'
    | '/vitrine/$storeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  BoutiquesRoute: typeof BoutiquesRoute
  ClientsRoute: typeof ClientsRoute
  ParametresRoute: typeof ParametresRoute
  VueEnsembleRoute: typeof VueEnsembleRoute
  CommandesOrderIdRoute: typeof CommandesOrderIdRoute
  FormulairesFormIdRoute: typeof FormulairesFormIdRoute
  FormulairesCommandeRoute: typeof FormulairesCommandeRoute
  FormulairesIntegrationsRoute: typeof FormulairesIntegrationsRoute
  FormulairesNouveauRoute: typeof FormulairesNouveauRoute
  FormulairesOffresRoute: typeof FormulairesOffresRoute
  ProduitsImportRoute: typeof ProduitsImportRoute
  ProduitsNouveauRoute: typeof ProduitsNouveauRoute
  CommandesIndexRoute: typeof CommandesIndexRoute
  FormulairesIndexRoute: typeof FormulairesIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  VitrineStoreIdProductIdRoute: typeof VitrineStoreIdProductIdRoute
  VitrineStoreIdIndexRoute: typeof VitrineStoreIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vue-ensemble': {
      id: '/vue-ensemble'
      path: '/vue-ensemble'
      fullPath: '/vue-ensemble'
      preLoaderRoute: typeof VueEnsembleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/': {
      id: '/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof CommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/$orderId': {
      id: '/commandes/$orderId'
      path: '/commandes/$orderId'
      fullPath: '/commandes/$orderId'
      preLoaderRoute: typeof CommandesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/': {
      id: '/formulaires/'
      path: '/formulaires'
      fullPath: '/formulaires/'
      preLoaderRoute: typeof FormulairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/$formId': {
      id: '/formulaires/$formId'
      path: '/formulaires/$formId'
      fullPath: '/formulaires/$formId'
      preLoaderRoute: typeof FormulairesFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/commande': {
      id: '/formulaires/commande'
      path: '/formulaires/commande'
      fullPath: '/formulaires/commande'
      preLoaderRoute: typeof FormulairesCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/integrations': {
      id: '/formulaires/integrations'
      path: '/formulaires/integrations'
      fullPath: '/formulaires/integrations'
      preLoaderRoute: typeof FormulairesIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/nouveau': {
      id: '/formulaires/nouveau'
      path: '/formulaires/nouveau'
      fullPath: '/formulaires/nouveau'
      preLoaderRoute: typeof FormulairesNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires/offres': {
      id: '/formulaires/offres'
      path: '/formulaires/offres'
      fullPath: '/formulaires/offres'
      preLoaderRoute: typeof FormulairesOffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/import': {
      id: '/produits/import'
      path: '/produits/import'
      fullPath: '/produits/import'
      preLoaderRoute: typeof ProduitsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/nouveau': {
      id: '/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/produits/nouveau'
      preLoaderRoute: typeof ProduitsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine/$storeId/': {
      id: '/vitrine/$storeId/'
      path: '/vitrine/$storeId'
      fullPath: '/vitrine/$storeId/'
      preLoaderRoute: typeof VitrineStoreIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine/$storeId/$productId': {
      id: '/vitrine/$storeId/$productId'
      path: '/vitrine/$storeId/$productId'
      fullPath: '/vitrine/$storeId/$productId'
      preLoaderRoute: typeof VitrineStoreIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  BoutiquesRoute: BoutiquesRoute,
  ClientsRoute: ClientsRoute,
  ParametresRoute: ParametresRoute,
  VueEnsembleRoute: VueEnsembleRoute,
  CommandesOrderIdRoute: CommandesOrderIdRoute,
  FormulairesFormIdRoute: FormulairesFormIdRoute,
  FormulairesCommandeRoute: FormulairesCommandeRoute,
  FormulairesIntegrationsRoute: FormulairesIntegrationsRoute,
  FormulairesNouveauRoute: FormulairesNouveauRoute,
  FormulairesOffresRoute: FormulairesOffresRoute,
  ProduitsImportRoute: ProduitsImportRoute,
  ProduitsNouveauRoute: ProduitsNouveauRoute,
  CommandesIndexRoute: CommandesIndexRoute,
  FormulairesIndexRoute: FormulairesIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  VitrineStoreIdProductIdRoute: VitrineStoreIdProductIdRoute,
  VitrineStoreIdIndexRoute: VitrineStoreIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
